authors:
  alexandros_koumparoulis:
    name: Alexandros Koumparoulis
    description: Senior Deep Learning Algorithm Engineer
    avatar: https://developer-blogs.nvidia.com/wp-content/uploads/2025/05/cropped-Screenshot-2025-05-09-at-1.51.17-AM-540x540.png
  wenwen_gao:
    name: Wenwen Gao
    description: NeMo Product Manager
    avatar: https://developer-blogs.nvidia.com/wp-content/uploads/2022/08/Wenwen-Headshot.jpg
  bernard_nguyen:
    name: Bernard Nguyen
    description: NeMo Engineering Director
    avatar: https://developer-blogs.nvidia.com/wp-content/uploads/2025/05/cropped-Bernard-Profile-540x540.png
  shashank_verma:
    name: Shashank Verma
    description: Product Research Engineering Manager
    avatar: https://developer-blogs.nvidia.com/wp-content/uploads/2025/05/image-2.png
  alexander_bukharin:
    name: Alexander Bukharin
    description: Applied Research Scientist
    avatar: https://developer-blogs.nvidia.com/wp-content/uploads/2025/07/cropped-alexander-bukharin-131x131.png
  terry_kong:
    name: Terry Kong
    description: Senior Deep Learning Algorithm Engineer
    avatar: https://developer-blogs.nvidia.com/wp-content/uploads/2024/12/Terry-Kong-131x131.jpg
  sylendran_arunagiri:
    name: Sylendran Arunagiri
    description: Technical Product Marketing Manager
    avatar: https://developer-blogs.nvidia.com/wp-content/uploads/2025/03/Sylendran-Arunagiri-131x131.jpg
  anna_shors:
    name: Anna Shors
    description: Senior Deep Learning Algorithm Engineer
    avatar: https://developer-blogs.nvidia.com/wp-content/uploads/2024/12/Anna-Shors-262x262.jpg
  parth_chadha:
    name: Parth Chadha
    description: Senior Deep Learning Algorithm Engineer
    avatar: https://developer-blogs.nvidia.com/wp-content/uploads/2021/12/Parth-Chadha.png
  huiying_li:
    name: Huiying Li
    description: Deep Learning Algorithm Engineer
    avatar: assets/images/authors/huiying_li.png
  sofia_kostandian:
    name: Sofia Kostandian
    description: Deep Learning Software Engineer
    avatar: https://developer-blogs.nvidia.com/wp-content/uploads/2024/07/Sofia-Kostandian.jpg
  nithin_rao_koluguri:
    name: Nithin Rao Koluguri
    description: Senior Research Scientist
    avatar: https://developer-blogs.nvidia.com/wp-content/uploads/2024/03/nithin-rao-koluguri.png
  guyue_huang:
    name: Guyue Huang
    description: Deep Learning Architect
    avatar: assets/images/authors/guyue_huang.png
  zhiyu_li:
    name: Zhiyul Li
    description: Deep Learning Algorithm Engineer
    avatar: assets/images/authors/zhiyu_li.png
  hemil_desai:
    name: Hemil Desai
    description: Senior Deep Learning Algorithm Engineer
    avatar: https://avatars.githubusercontent.com/hemildesai
  yifu_wu:
    name: Yi-Fu Wu
    description: Deep Learning Algorithm Engineer
    avatar: assets/images/authors/yifu_wu.png
  rohit_jena:
    name: Rohit Jena
    description: Deep Learning Research Intern
    avatar: assets/images/authors/rohit_jena.png
  hao_zhang:
    name: Hao Zhang
    description: Reseach Scientist
    avatar: assets/images/authors/hao_zhang.png
  mingjie_liu:
    name: Mingjie Liu
    description: Reseach Scientist
    avatar: assets/images/authors/mingjie_liu.png
  shaokun_zhang:
    name: Shaokun Zhang
    description: PhD Student
    avatar: assets/images/authors/shaokun_zhang.png
  yi_dong:
    name: Yi Dong
    description: Principal Reseach Scientist
    avatar: assets/images/authors/yi_dong.png
  yuki_huang:
    name: Yuki Huang
    description: Deep Learning Engineer
    avatar: assets/images/authors/yuki_huang.png
  jan_kautz:
    name: Jan Kautz
    description: Vice President of Research
    avatar: assets/images/authors/jan_kautz.png
  jian_hu:
    name: Jian Hu
    description: Senior Deep Learning Engineer
    avatar: assets/images/authors/jian_hu.png
  alex_qiu:
    name: Zhaopeng Qiu
    description: Solution Architect
    avatar: assets/images/authors/alex_qiu.jpg
  shuo_yang:
    name: Shuo Yang
    description: Solution Architect
    avatar: assets/images/authors/shuo_yang.jpg
  shuang_yu:
    name: Shuang Yu
    description: Solution Architect
    avatar: assets/images/authors/shuang_yu.png
  sharath_turuvekere_sreenivas:
    name: Sharath Turuvekere Sreenivas
    description: Senior Deep Learning Algorithm Engineer
    avatar: assets/images/authors/sharath_ts.png
  aditya_vavre:
    name: Aditya Vavre
    description: Deep Learning Algorithm Engineer
    avatar: assets/images/authors/avavre.png
  nima_tajbakhsh:
    name: Nima Tajbakhsh
    description: NeMo Engineering Manager
    avatar: assets/images/authors/nima_tajbakhsh.png