authors:
  alexandros_koumparoulis:
    name: Alexandros Koumparoulis
    description: Senior Deep Learning Algorithm Engineer
    avatar: https://developer-blogs.nvidia.com/wp-content/uploads/2025/05/cropped-Screenshot-2025-05-09-at-1.51.17-AM-540x540.png
  wenwen_gao:
    name: Wenwen Gao
    description: NeMo Product Manager
    avatar: https://developer-blogs.nvidia.com/wp-content/uploads/2022/08/Wenwen-Headshot.jpg
  bernard_nguyen:
    name: Bernard Nguyen
    description: NeMo Engineering Director
    avatar: https://developer-blogs.nvidia.com/wp-content/uploads/2025/05/cropped-Bernard-Profile-540x540.png
  shashank_verma:
    name: Shashank Verma
    description: Product Research Engineering Manager
    avatar: https://developer-blogs.nvidia.com/wp-content/uploads/2025/05/image-2.png
  alexander_bukharin:
    name: Alexander Bukharin
    description: Applied Research Scientist
    avatar: https://developer-blogs.nvidia.com/wp-content/uploads/2025/07/cropped-alexander-bukharin-131x131.png
  terry_kong:
    name: Terry Kong
    description: Senior Deep Learning Algorithm Engineer
    avatar: https://developer-blogs.nvidia.com/wp-content/uploads/2024/12/Terry-Kong-131x131.jpg
  sylendran_arunagiri:
    name: Sylendran Arunagiri
    description: Technical Product Marketing Manager
    avatar: https://developer-blogs.nvidia.com/wp-content/uploads/2025/03/Sylendran-Arunagiri-131x131.jpg